### ISSUE TITLE
[Docs] Add a tutorial to push the build result to GitHub Pages

### ISSUE THREAD

**Issue by nhoizey** [tweetback/tweetback#14]
To ease sharing the tweets archive by users without much technical knowledge, having a clear tutorial about how to do it with GitHub Pages would be nice.

It would also help when the archive files (`tweets.js`, `tweet.db`) weight more than 50MB and can't be added to a GitHub repository:
- #4

**Comment by steren** [comment]
What I did for https://github.com/steren/twitter was to only store the output to the repo managed where I enable GitHub pages 

So the tutorial should be:


1. go into `_site`
2. Do `git init`
3. add all files from that folder
4. Commit
5. Create a new GitHub repo
6. Enable GitHub pages in repo Settings
7. Add remote 
8. push

**Comment by nhoizey** [comment]
@steren could you create a `docs/deploy-with-github-pages.md` file with these instructions?
