### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by zachleat** [tweetback/tweetback#23]
I’d love to see a simple (maybe serverless) search for tweet content.

**Comment by Accudio** [comment]
A very low-hanging option for this is using a package that generates a static search index. Within a few minutes I had managed to set up Pagefind https://github.com/cloudcannon/pagefind on my archive to search all tweets: https://twitter.alistairshepherd.uk/search/

It runs on the `eleventy.after` event and generates a static index by crawling the pages in the output directory, and includes a relatively small library and UI component to output the results.

It certainly isn't an ideal solution as it runs the search locally therefore requiring a decent amount of JS and not having a server-side fallback, but on the other hand doesn't rely on serverless routes making hosting a bit easier.

I'd be keen to hear thoughts on this solution, and happy to put together a PR based on my implementation of pagefind if it's wanted.

**Comment by nhoizey** [comment]
@Accudio it works great! 👍

I like that [Pagefind’s search index is split into chunks](https://pagefind.app/#:~:text=pagefind%E2%80%99s%20search%20index%20is%20split%20into%20chunks), as other similar solutions generate one single very big file, which would not work well with my ~120.000 tweets… 😅

I think a PR for this would be great!

**Comment by Accudio** [comment]
I've added a basic Pagefind implemention in PR #27 although we may want to do a bit more with it including a custom search component!

**Comment by nhoizey** [comment]
Done in #27, thanks @Accudio ! 🙏
