### ISSUE TITLE
Meta description is unhelpfully generic for tweet pages

### ISSUE THREAD

**Issue by stuartlangridge** [tweetback/tweetback#31]
The meta description for tweetback-generated pages is akin to "A read-only indieweb self-hosted archive of all 68141 of sil’s tweets." This is rather unhelpful for individual tweet pages, because when you paste a link into anywhere else -- a chat app, for example -- then it fetches this description and shows it. Actual tweets contain the content of the tweet in these descriptions, which would be a lot more helpful; this means that pasting a link to a tweet shows the content to people viewing it and they don't have to follow the link.

I've looked at layout.11ty.js so I can see where this generic description comes from, but I don't know enough 11ty to know how to make the individual tweet pages include something better.

**Comment by zachleat** [comment]
You will just want to use a `data` variable in the layout file and then set that variable in `tweet-pages.js`.

Here’s an example of it on my site using `liquid` https://github.com/zachleat/zachleat.com/blob/2ea4b723aae4a87bd9f533d52be319369f0e6fe0/_includes/layouts/base.liquid#L25

But you’ll want to apply this to this layout file: https://github.com/tweetback/tweetback/blob/bfa2a3053c9e73e12d1f2b6c52cbf07f481adce9/_includes/layout.11ty.js#L39 and then set that variable in the page here: https://github.com/tweetback/tweetback/blob/bfa2a3053c9e73e12d1f2b6c52cbf07f481adce9/tweet-pages.11ty.js

You can read more about the Eleventy Data Cascade here: https://www.11ty.dev/docs/data-cascade/

**Comment by aarongustafson** [comment]
Closed by #34
