### ISSUE TITLE
Transforming twitter urls to nitter urls

### ISSUE THREAD

**Issue by reggi** [tweetback/tweetback#59]
You may also want to consider transforming all twitter links in your archive to nitter https://nitter.snopyta.org/zachleat, for example rather than linking to https://twitter.com/buildWithLit/status/1591173922678079489 you can link to https://nitter.snopyta.org/buildWithLit/status/1591173922678079489 details about nitter https://nitter.snopyta.org/about, this can act as a fallback if they haven't created their own archive (🔗[from mastodon](https://indieweb.social/@thomasreggi/109383678819245922))

Another idea could be to somehow personally archive all interactions, so you never leave your site, you'd host a version of that one-off `@buildWithLit` tweet (and any others you've linked in a tweet). Reminds me of how site-sucker works if you configure it to run "deep" https://ricks-apps.com/osx/sitesucker/index.html

**Comment by nhoizey** [comment]
@reggi there are two topics here.

Could you open a second issue for the second topic, and we can discuss Nitter here?

**Comment by cooljeanius** [comment]
Note that Nitter has died recently, due to Twitter API changes
