### ISSUE TITLE
Limit collection generation?

### ISSUE THREAD

**Issue by hteumeuleu** [tweetback/tweetback#93]
I'd like to tweak my instance of Tweetback and edit the styles and general layout. But editing the layout regenerates the entire site and it takes hours for me. Is there a way to limit the collection of tweets to only a few so I can edit the layout painlessly? 

I found [this issue](https://github.com/11ty/eleventy/discussions/3025) in Eleventy mentioning something similar, but I have no idea how I could apply this in Tweetback.

**Comment by nhoizey** [comment]
@hteumeuleu you may not need this a few months later, but I currently use `eleventyConfig.ignores.add()` to do this for one of my sites: https://github.com/nhoizey/nicolas-hoizey.com/blob/main/.eleventy.js#L300-L308

**Comment by hteumeuleu** [comment]
You're right that I no longer need this. But I guess this fixes it, so I'll close the issue. Thank you!
