### ISSUE TITLE
Mastodon verification

### ISSUE THREAD

**Issue by cooljeanius** [tweetback/tweetback#97]
I recently added a link to my Tweetback archive to my Mastodon profile. It would be nice if there were an easy way to make the link turn green to verify that it's actually mine.

**Comment by halkeye** [comment]
are you just asking for a meta tag?
according to https://joinmastodon.org/verification you just need a rel="me"
so add 
`<link rel="me" value="your mastodon link" />` to https://github.com/tweetback/tweetback/blob/main/_includes/layout.11ty.js#L43

**Comment by cooljeanius** [comment]
> are you just asking for a meta tag? according to [joinmastodon.org/verification](https://joinmastodon.org/verification) you just need a rel="me" so add `<link rel="me" value="your mastodon link" />` to [`main`/_includes/layout.11ty.js#L43](https://github.com/tweetback/tweetback/blob/main/_includes/layout.11ty.js?rgh-link-date=2024-03-27T00%3A00%3A15Z#L43)

thanks, but I just tried that, and it didn't work; the link isn't green yet:
<img width="601" alt="Screen Shot 2024-04-09 at 21 09 54" src="https://github.com/tweetback/tweetback/assets/1388660/25036155-cc1f-49d9-8658-7097cde1fecd">

**Comment by halkeye** [comment]
https://opensource.com/article/22/11/verified-mastodon-website says it should be an anchor (a) tag
https://fedi.tips/how-do-i-verify-my-account/ says it should be link href not link value

I guess i got the original html wrong, the first link says there's a UI that tells you exactly what to put.

**Comment by cooljeanius** [comment]
> [opensource.com/article/22/11/verified-mastodon-website](https://opensource.com/article/22/11/verified-mastodon-website) says it should be an anchor (a) tag [fedi.tips/how-do-i-verify-my-account](https://fedi.tips/how-do-i-verify-my-account/) says it should be link href not link value
> 
> I guess i got the original html wrong, the first link says there's a UI that tells you exactly what to put.

Tried it like that, but it still doesn't seem to be turning green yet...

**Comment by halkeye** [comment]
You put an anchor in the header. That's not a thing.

I'm going to again suggest reading instead of just guessing. I was just trying to point you in the direction not giving you an exact solution (as it's not a problem I'm having)

**Comment by cooljeanius** [comment]
OK I figured it out... still a bit trickier than I think it ought to be, but I guess I can close...
